---
  - name: create /etc/kubernetes/specs directory
    file:
      path: "{{ kubernetes_spec_dir }}"
      state: directory

  - name: copy hostpath-pv.yaml to remote
    template:
      src: hostpath-pv.yaml
      dest: "{{ kubernetes_spec_dir }}/heapster-pv.yaml"
    when: >
      heapster_monitoring_persistent_volume_enabled|bool == false and
      (heapster_monitoring_persistent_volume_claim_path is not defined or
      heapster_monitoring_persistent_volume_claim_path == '')
  - name: copy pvc spec to remote
    template:
      src: "{% if heapster_monitoring_persistent_volume_claim_path is defined and heapster_monitoring_persistent_volume_claim_path != '' %}{{ heapster_monitoring_persistent_volume_claim_path }}{% else %}pvc.yaml{% endif %}"
      dest: "{{ kubernetes_spec_dir }}/heapster-pvc.yaml"
  - name: copy heapster-rbac.yaml to remote
    template:
      src: heapster-rbac.yaml
      dest: "{{ kubernetes_spec_dir }}/heapster-rbac.yaml"
  - name: copy influxdb.yaml to remote
    template:
      src: influxdb.yaml
      dest: "{{ kubernetes_spec_dir }}/influxdb.yaml"
  - name: copy heapster.yaml to remote
    template:
      src: heapster.yaml
      dest: "{{ kubernetes_spec_dir }}/heapster.yaml"

  - name: create heapster hostPath volume
    command: kubectl apply -f {{ kubernetes_spec_dir }}/heapster-pv.yaml
    when: >
      heapster_monitoring_persistent_volume_enabled|bool == false and
      (heapster_monitoring_persistent_volume_claim_path is not defined or
      heapster_monitoring_persistent_volume_claim_path == '')
  - name: create heapster pvc
    command: kubectl apply -f {{ kubernetes_spec_dir }}/heapster-pvc.yaml
  - name: create heapster rolebinding
    command: kubectl apply -f {{ kubernetes_spec_dir }}/heapster-rbac.yaml
  - name: start influxdb controller
    command: kubectl apply -f {{ kubernetes_spec_dir }}/influxdb.yaml
  - name: start heapster controller
    command: kubectl apply -f {{ kubernetes_spec_dir }}/heapster.yaml

  - name: validate heapster pods
    include: validate.yaml
    when: heapster_monitoring_persistent_volume_claim_path is not defined or heapster_monitoring_persistent_volume_claim_path == ''
